// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

// The following is brought in by the endianness component, which all
// applications must include
#include "sl_endianness.h"

#ifndef SILABS_AF_ENDPOINT_CONFIG
#define SILABS_AF_ENDPOINT_CONFIG 1

// Default values for the attributes longer than a pointer, in a form of a
// binary blob. All attribute values with size greater than 2 bytes. Excluding 0
// values and externally saved values. Separate block is generated for
// big-endian and little-endian cases.

#define ZCL_GENERATED_DEFAULTS_COUNT (4)

#if BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0x04, 'I', 'C', 'T', 'U', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 0,DEFAULT value for cluster: Basic, attribute: manufacturer name, side: server */ \
  0x0E, 'S', 'm', 'a', 'r', 't', 'I', 'V', '-', 'S', 'e', 'n', 's', 'o', 'r', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 33,DEFAULT value for cluster: Basic, attribute: model identifier, side: server */ \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 66,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 74,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#else //!BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0x04, 'I', 'C', 'T', 'U', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 0,DEFAULT value for cluster: Basic, attribute: manufacturer name, side: server */ \
  0x0E, 'S', 'm', 'a', 'r', 't', 'I', 'V', '-', 'S', 'e', 'n', 's', 'o', 'r', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 33,DEFAULT value for cluster: Basic, attribute: model identifier, side: server */ \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 66,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 74,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#endif


// This is an array of sl_zigbee_af_attribute_min_max_value_t structures.

#define ZCL_GENERATED_MIN_MAX_DEFAULT_COUNT (0)
	#define ZCL_GENERATED_MIN_MAX_DEFAULTS { { { .ptrToDefaultValue = (uint8_t*)0x00 }, { .ptrToDefaultValue = (uint8_t*)0x00 }, { .ptrToDefaultValue = (uint8_t*)0x00 } } }


#define ZCL_GENERATED_ATTRIBUTE_COUNT (37)

// This is an array of sl_zigbee_af_attribute_metadata_t structures.
#define ZCL_GENERATED_ATTRIBUTES { \
  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0x08  } }, /* 0 Cluster: Basic, Attribute: ZCL version, Side: server*/ \
		  { 0x0004, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)&(generatedDefaults[0]) } }, /* 1 Cluster: Basic, Attribute: manufacturer name, Side: server*/ \
	  { 0x0005, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)&(generatedDefaults[33]) } }, /* 2 Cluster: Basic, Attribute: model identifier, Side: server*/ \
	  { 0x0007, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0x00  } }, /* 3 Cluster: Basic, Attribute: power source, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)3  } }, /* 4 Cluster: Basic, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_IEEE_ADDRESS_ATTRIBUTE_TYPE, 8, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[66]) } }, /* 5 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Server ID, Side: client*/ \
	  { 0x0001, ZCL_INT32U_ATTRIBUTE_TYPE, 4, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[74]) } }, /* 6 Cluster: Over the Air Bootloading, Attribute: Offset (address) into the file, Side: client*/ \
	  { 0x0006, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0x00  } }, /* 7 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Status, Side: client*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)4  } }, /* 8 Cluster: Over the Air Bootloading, Attribute: cluster revision, Side: client*/ \
		  { 0x0000, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 9 Cluster: Smart IV Vitals, Attribute: HeartRate, Side: server*/ \
		  { 0x0001, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 10 Cluster: Smart IV Vitals, Attribute: Spo2, Side: server*/ \
		  { 0x0002, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 11 Cluster: Smart IV Vitals, Attribute: FlowRatio, Side: server*/ \
		  { 0x0003, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 12 Cluster: Smart IV Vitals, Attribute: DropRatio, Side: server*/ \
		  { 0x0004, ZCL_BITMAP16_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 13 Cluster: Smart IV Vitals, Attribute: AlarmBitmap, Side: server*/ \
		  { 0x0005, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 14 Cluster: Smart IV Vitals, Attribute: WeightG, Side: server*/ \
		  { 0x0006, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 15 Cluster: Smart IV Vitals, Attribute: DropsPerMin, Side: server*/ \
		  { 0x0007, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0064  } }, /* 16 Cluster: Smart IV Vitals, Attribute: TargetFlowMlH, Side: server*/ \
		  { 0x0008, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0014  } }, /* 17 Cluster: Smart IV Vitals, Attribute: TargetDropsPerMin, Side: server*/ \
		  { 0x0009, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 18 Cluster: Smart IV Vitals, Attribute: TareCommand, Side: server*/ \
		  { 0x000A, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 19 Cluster: Smart IV Vitals, Attribute: HrRecalibrateCommand, Side: server*/ \
		  { 0x000B, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 20 Cluster: Smart IV Vitals, Attribute: HrBaselineSecondsRemaining, Side: server*/ \
		  { 0x000C, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 21 Cluster: Smart IV Vitals, Attribute: HrBaselineBpm, Side: server*/ \
		  { 0x000D, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 22 Cluster: Smart IV Vitals, Attribute: TareEventCount, Side: server*/ \
		  { 0x000E, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 23 Cluster: Smart IV Vitals, Attribute: HrBaselineEventCount, Side: server*/ \
		  { 0x000F, ZCL_BITMAP16_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 24 Cluster: Smart IV Vitals, Attribute: TsFlags, Side: server*/ \
		  { 0x0010, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 25 Cluster: Smart IV Vitals, Attribute: HrForecast16s, Side: server*/ \
		  { 0x0011, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 26 Cluster: Smart IV Vitals, Attribute: Spo2Forecast16s, Side: server*/ \
		  { 0x0012, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 27 Cluster: Smart IV Vitals, Attribute: HrTrendBpmPerMin, Side: server*/ \
		  { 0x0013, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 28 Cluster: Smart IV Vitals, Attribute: TsAnomalyScoreX100, Side: server*/ \
		  { 0x0014, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 29 Cluster: Smart IV Vitals, Attribute: DropsForecast16s, Side: server*/ \
		  { 0x0015, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 30 Cluster: Smart IV Vitals, Attribute: DropsTrendDpmPerMin, Side: server*/ \
		  { 0x0016, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 31 Cluster: Smart IV Vitals, Attribute: RemainingMl, Side: server*/ \
		  { 0x0017, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 32 Cluster: Smart IV Vitals, Attribute: RemainingMin, Side: server*/ \
		  { 0x0018, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 33 Cluster: Smart IV Vitals, Attribute: MonitoringActive, Side: server*/ \
		  { 0x0019, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 34 Cluster: Smart IV Vitals, Attribute: DropTrainingSamples, Side: server*/ \
		  { 0x001A, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 35 Cluster: Smart IV Vitals, Attribute: VitalsTrainingSamples, Side: server*/ \
		  { 0x001B, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } } /* 36 Cluster: Smart IV Vitals, Attribute: AlertsArmed, Side: server*/ \
		 }

 

#define ZCL_GENERATED_CLUSTER_COUNT (3)
	
// This is an array of sl_zigbee_af_cluster_t structures.
#define ZCL_GENERATED_CLUSTERS { \
  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 5, 0, CLUSTER_MASK_SERVER, NULL }, /* 0, Endpoint Id: 1, Cluster: Basic, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[5]), 4, 15, CLUSTER_MASK_CLIENT, NULL }, /* 1, Endpoint Id: 1, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0xFC01, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[9]), 28, 47, CLUSTER_MASK_SERVER, NULL } /* 2, Endpoint Id: 2, Cluster: Smart IV Vitals, Side: server*/ \
	 }

 
#define ZCL_GENERATED_ENDPOINT_TYPE_COUNT (2)

// This is an array of sl_zigbee_af_endpoint_type_t structures.
#define ZCL_GENERATED_ENDPOINT_TYPES { \
  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[0])), 2, 15 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[2])), 1, 47 }, \
	 } 
// Largest attribute size is needed for various buffers
#define ZCL_ATTRIBUTE_LARGEST (33)

// Total size of singleton attributes
#define ZCL_ATTRIBUTE_SINGLETONS_SIZE (70)

// Total size of attribute storage
#define ZCL_ATTRIBUTE_MAX_SIZE (62)

// Number of fixed endpoints	
#define ZCL_FIXED_ENDPOINT_COUNT (2)

// Array of endpoints that are supported, the data inside the array is the
// endpoint number.
#define ZCL_FIXED_ENDPOINT_ARRAY { \
  1, \
  2 \
}

// Array of profile ids
#define ZCL_FIXED_PROFILE_IDS { \
  260, \
  260 \
}

// Array of device ids
#define ZCL_FIXED_DEVICE_IDS { \
  65535, \
  65535 \
}

// Array of device versions
#define ZCL_FIXED_DEVICE_VERSIONS { \
  1, \
  1 \
}

// Array of endpoint types supported on each endpoint
#define ZCL_FIXED_ENDPOINT_TYPES { \
  0, \
  1 \
}

// Array of networks supported on each endpoint
#define ZCL_FIXED_NETWORKS { \
  0, \
  0 \
}

// Array of sl_zigbee_af_command_metadata_t structs.
#define ZCL_ZAP_COMMAND_MASK(mask) COMMAND_MASK_ ## mask
#define SL_ZIGBEE_ZCL_GENERATED_COMMAND_COUNT  (7)
#define ZCL_GENERATED_COMMANDS { \
  { 0x0019, 0x00, COMMAND_MASK_INCOMING_CLIENT }, /* 0, Cluster: Over the Air Bootloading, Command: ImageNotify*/ \
	  { 0x0019, 0x01, COMMAND_MASK_OUTGOING_CLIENT }, /* 1, Cluster: Over the Air Bootloading, Command: QueryNextImageRequest*/ \
	  { 0x0019, 0x02, COMMAND_MASK_INCOMING_CLIENT }, /* 2, Cluster: Over the Air Bootloading, Command: QueryNextImageResponse*/ \
	  { 0x0019, 0x03, COMMAND_MASK_OUTGOING_CLIENT }, /* 3, Cluster: Over the Air Bootloading, Command: ImageBlockRequest*/ \
	  { 0x0019, 0x05, COMMAND_MASK_INCOMING_CLIENT }, /* 4, Cluster: Over the Air Bootloading, Command: ImageBlockResponse*/ \
	  { 0x0019, 0x06, COMMAND_MASK_OUTGOING_CLIENT }, /* 5, Cluster: Over the Air Bootloading, Command: UpgradeEndRequest*/ \
	  { 0x0019, 0x07, COMMAND_MASK_INCOMING_CLIENT }, /* 6, Cluster: Over the Air Bootloading, Command: UpgradeEndResponse*/ \
	 } 
// Array of sl_zigbee_af_manufacturer_code_entry_t structures for commands.
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODES { \
  { 0x00, 0x00 }  \
							 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for clusters.
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODE_COUNT (1)
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODES { \
		  { 2, 0x1049 },  \
	 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for attributes.
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODE_COUNT (28)
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODES { \
									  { 9, 0x1049 },  \
	  { 10, 0x1049 },  \
	  { 11, 0x1049 },  \
	  { 12, 0x1049 },  \
	  { 13, 0x1049 },  \
	  { 14, 0x1049 },  \
	  { 15, 0x1049 },  \
	  { 16, 0x1049 },  \
	  { 17, 0x1049 },  \
	  { 18, 0x1049 },  \
	  { 19, 0x1049 },  \
	  { 20, 0x1049 },  \
	  { 21, 0x1049 },  \
	  { 22, 0x1049 },  \
	  { 23, 0x1049 },  \
	  { 24, 0x1049 },  \
	  { 25, 0x1049 },  \
	  { 26, 0x1049 },  \
	  { 27, 0x1049 },  \
	  { 28, 0x1049 },  \
	  { 29, 0x1049 },  \
	  { 30, 0x1049 },  \
	  { 31, 0x1049 },  \
	  { 32, 0x1049 },  \
	  { 33, 0x1049 },  \
	  { 34, 0x1049 },  \
	  { 35, 0x1049 },  \
	  { 36, 0x1049 },  \
	 } 
// Array of sl_zigbee_af_plugin_reporting_entry_t structures.
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS_TABLE_SIZE (26)
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS { \
  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0000, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HeartRate */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0001, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: Spo2 */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0002, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: FlowRatio */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0003, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropRatio */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0004, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: AlarmBitmap */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0005, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: WeightG */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0006, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropsPerMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0007, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TargetFlowMlH */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0008, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TargetDropsPerMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000B, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrBaselineSecondsRemaining */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000C, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrBaselineBpm */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000D, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TareEventCount */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000E, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrBaselineEventCount */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000F, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TsFlags */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0010, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrForecast16s */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0011, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: Spo2Forecast16s */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0012, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrTrendBpmPerMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0013, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TsAnomalyScoreX100 */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0014, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropsForecast16s */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0015, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropsTrendDpmPerMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0016, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: RemainingMl */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0017, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: RemainingMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0018, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: MonitoringActive */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0019, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropTrainingSamples */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x001A, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: VitalsTrainingSamples */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x001B, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: AlertsArmed */ \
	 } 

#define SL_ZIGBEE_ZCL_MANUFACTURER_CODE 0x1049
#define SL_ZIGBEE_AF_DEFAULT_RESPONSE_POLICY_ALWAYS

// All Enabled Clusters
#define ZCL_USING_BASIC_CLUSTER_SERVER
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLIENT
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_SERVER

// Cluster Counts
#define SL_ZIGBEE_ZCL_BASIC_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_OTA_BOOTLOAD_CLUSTER_CLIENT_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_SMART_IV_VITALS_CLUSTER_SERVER_ENDPOINT_COUNT (1)

// All Enabled Cluster Attributes
#define ZCL_USING_BASIC_CLUSTER_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MANUFACTURER_NAME_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MODEL_IDENTIFIER_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_POWER_SOURCE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_UPGRADE_SERVER_ID_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_FILE_OFFSET_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_IMAGE_UPGRADE_STATUS_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HEART_RATE_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_SPO2_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_FLOW_RATIO_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROP_RATIO_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_ALARM_BITMAP_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_WEIGHT_G_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROPS_PER_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARGET_FLOW_ML_H_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARGET_DROPS_PER_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARE_COMMAND_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_RECALIBRATE_COMMAND_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_BASELINE_SECONDS_REMAINING_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_BASELINE_BPM_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARE_EVENT_COUNT_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_BASELINE_EVENT_COUNT_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TS_FLAGS_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_FORECAST_16_S_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_SPO2_FORECAST_16_S_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_TREND_BPM_PER_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TS_ANOMALY_SCORE_X100_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROPS_FORECAST_16_S_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROPS_TREND_DPM_PER_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_REMAINING_ML_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_REMAINING_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_MONITORING_ACTIVE_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROP_TRAINING_SAMPLES_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_VITALS_TRAINING_SAMPLES_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_ALERTS_ARMED_ATTRIBUTE

#define SL_ZIGBEE_AF_SUPPORT_COMMAND_DISCOVERY


#endif // SILABS_AF_ENDPOINT_CONFIG