#!/usr/bin/env python3
"""
Turn the three .tflite models into C sources, using Silicon Labs' own MLTK tool.

--- Why not just write a byte array ------------------------------------------

Emitting `const uint8_t model[] = {0x1c, 0x00, ...}` is ten lines of Python. The
reason to drive the vendor tool instead is the file it generates alongside the
array: `sl_tflite_micro_opcode_resolver.h`, whose contents are derived by PARSING
THE FLATBUFFER. It contains exactly the operators the model actually uses, sized
exactly right:

    static tflite::MicroMutableOpResolver<3> opcode_resolver;
    opcode_resolver.AddConv2D();
    opcode_resolver.AddReshape();
    opcode_resolver.AddFullyConnected();

Hand-written resolvers are where this kind of project rots. Change a model's
architecture, forget to add the new operator, and the firmware fails at
AllocateTensors - at the bedside, not at build time. Generating the resolver from
the model makes that class of mistake impossible.

--- Why the tool is invoked here rather than through config/tflite/ ----------

Simplicity Studio runs this converter automatically for any .tflite dropped into
`config/tflite/`, and that is the path the project would use if it had one model.
It has three, and `flatbuffer_converter.py::find_first_tflite_file` takes only the
first file it finds. So the tool is invoked directly, once per model, and the
symbols it emits are renamed per model - the generated code is identical to what
Studio would produce, just three times over with distinct names.

--- Two patches applied to the vendor tool -----------------------------------

Neither modifies anything inside the SDK; both are applied to the import
environment here.

1. `imp` shim. The `flatbuffers` package Silicon Labs vendors with the tool still
   does `import imp`, a module removed in Python 3.12. It uses it for exactly one
   call, `imp.find_module('numpy')`, so a stub with that one function is enough.

2. `sys.path` injection, because the tool is not an installed package.

Requires `pyyaml` and `jinja2` in the environment (the tool's own dependencies).
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import runpy
import shutil
import sys
import tempfile
import types
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MODELS = REPO / "ml" / "models"
DEST = REPO / "firmware" / "models"

PART_NUMBER = "EFR32MG26B510F3200IM48"

# (tflite file, C symbol stem, uppercase macro stem)
TARGETS = [
    ("drip_forecaster_int8.tflite", "drip", "DRIP"),
    ("vitals_forecaster_int8.tflite", "vitals", "VITALS"),
    ("vitals_ae_int8.tflite", "ae", "AE"),
]


def find_converter() -> Path:
    """Locate the MLTK flatbuffer converter inside the installed AIML extension."""
    roots = [Path.home() / ".silabs", REPO]
    for root in roots:
        for hit in root.glob("**/tool/flatbuffer-converter/flatbuffer_converter.py"):
            return hit
    raise SystemExit(
        "Could not find flatbuffer_converter.py. It ships with the Silicon Labs "
        "AIML SDK extension; install it via Simplicity Studio or point --tool at it."
    )


def install_imp_shim() -> None:
    """Provide the one function the vendored flatbuffers package needs."""
    if "imp" in sys.modules:
        return
    shim = types.ModuleType("imp")

    def find_module(name, path=None):
        if importlib.util.find_spec(name) is None:
            raise ImportError(name)
        return None

    shim.find_module = find_module
    sys.modules["imp"] = shim


def run_converter(tool: Path, tflite: Path, out_dir: Path) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        in_dir = Path(tmp) / "in"
        in_dir.mkdir()
        shutil.copy(tflite, in_dir / tflite.name)

        saved_argv, saved_path = sys.argv, list(sys.path)
        sys.path.insert(0, str(tool.parent))
        sys.argv = [tool.name, "generate", str(in_dir), str(out_dir), PART_NUMBER]
        try:
            runpy.run_path(str(tool), run_name="__main__")
        except SystemExit as exc:            # the tool calls sys.exit() on success
            if exc.code not in (None, 0):
                raise
        finally:
            sys.argv, sys.path = saved_argv, saved_path
            # The tool leaves its own modules imported; drop them so the next
            # model is generated by a clean import rather than stale state.
            for name in [m for m in sys.modules
                         if m.split(".")[0] in {"tflite", "tflite_model",
                                                "flatbuffers",
                                                "tflite_model_parameters",
                                                "tensorflow_lite_support"}]:
                del sys.modules[name]


def rename_symbols(text: str, stem: str, macro: str) -> str:
    """Give this model's generated code names that will not collide."""
    return (
        text.replace("sl_tflite_model_array", f"g_{stem}_model_array")
        .replace("sl_tflite_model_len", f"g_{stem}_model_len")
        .replace("SL_TFLITE_MICRO_OPCODE_RESOLVER_H", f"{macro}_OPCODE_RESOLVER_H")
        .replace("SL_TFLITE_MICRO_OPCODE_RESOLVER", f"{macro}_OPCODE_RESOLVER")
        .replace("SL_TFLITE_MICRO_MODEL_H", f"{macro}_MODEL_H")
        .replace("sl_tflite_micro_model.h", f"model_{stem}.h")
        .replace("opcode_resolver", f"{stem}_opcode_resolver")
    )


BANNER = """/* GENERATED FILE - DO NOT EDIT.
 *
 * Produced by ml/export_c_headers.py from {src}, using Silicon Labs' own MLTK
 * flatbuffer converter (the same tool Simplicity Studio runs on a .tflite placed
 * in config/tflite/). Regenerate with:
 *
 *     .venv-ai/bin/python ml/export_c_headers.py
 */
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tool", type=Path, default=None)
    ap.add_argument("--dest", type=Path, default=DEST)
    args = ap.parse_args()

    tool = args.tool or find_converter()
    print(f"MLTK converter: {tool}")
    install_imp_shim()

    args.dest.mkdir(parents=True, exist_ok=True)
    manifest = {}

    for tflite_name, stem, macro in TARGETS:
        tflite = MODELS / tflite_name
        if not tflite.exists():
            raise SystemExit(f"Missing {tflite} - train the model first")

        with tempfile.TemporaryDirectory() as tmp:
            gen = Path(tmp)
            run_converter(tool, tflite, gen)

            produced = {p.name: p for p in gen.iterdir()}
            required = {"sl_tflite_micro_model.h", "sl_tflite_micro_model.c",
                        "sl_tflite_micro_opcode_resolver.h"}
            missing = required - produced.keys()
            if missing:
                raise SystemExit(f"{tflite_name}: converter did not emit {missing}")

            outputs = {
                "sl_tflite_micro_model.h": f"model_{stem}.h",
                "sl_tflite_micro_model.c": f"model_{stem}.c",
                "sl_tflite_micro_opcode_resolver.h": f"model_{stem}_opcodes.h",
            }
            for src_name, dst_name in outputs.items():
                text = rename_symbols(produced[src_name].read_text(), stem, macro)
                banner = BANNER.format(src=f"ml/models/{tflite_name}")
                (args.dest / dst_name).write_text(banner + text)

            resolver = (args.dest / f"model_{stem}_opcodes.h").read_text()
            ops = sorted(
                line.strip().split(".")[1].split("(")[0]
                for line in resolver.splitlines()
                if "_opcode_resolver.Add" in line
            )
            manifest[stem] = {
                "tflite": f"ml/models/{tflite_name}",
                "bytes": tflite.stat().st_size,
                "operators": ops,
                "files": sorted(outputs.values()),
            }
            print(f"  {stem:7s} {tflite.stat().st_size:6d} B  "
                  f"resolver<{len(ops)}>: {', '.join(ops)}")

    (args.dest / "models_manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"\nGenerated into {args.dest.relative_to(REPO)}")


if __name__ == "__main__":
    main()
