<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HisServer.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Update="chip_sample.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/HisServer/HisServer.csproj" />
  </ItemGroup>
</Project>
